apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rds-mysql
  namespace: default
spec:
  type: bindings.mysql
  version: v1
  metadata:
    - name: url # Required, define DB connection in DSN format
      secretKeyRef:
        name: mysql-connect
        key: connection_string
    - name: maxIdleConns
      value: "10"
    - name: maxOpenConns
      value: "10"
    - name: connMaxLifetime
      value: "12s"
    - name: connMaxIdleTime
      value: "12s"
