apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rds-mysql
  namespace: default
spec:
  type: bindings.mysql
  version: v1
  metadata:
    - name: url # Required, define DB connection in DSN format
      value: "root:Cloud@1234@tcp(172.16.0.88:3306)/dapr_schema?allowNativePasswords=true"
    - name: maxIdleConns
      value: "10"
    - name: maxOpenConns
      value: "10"
    - name: connMaxLifetime
      value: "12s"
    - name: connMaxIdleTime
      value: "12s"
