apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: 172.16.0.87:6379
  - name: redisPassword
    secretKeyRef:
      name: redis-pass
      key: passowrd